# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-oauth/',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/nbdev-oauth/',
                'lib_path': 'nbdev-oauth'},
  'syms': {'nbdev-oauth.core': {'nbdev-oauth.core.foo': ('core.html#foo', 'nbdev-oauth/core.py')}}}
